export const ADDRECIPE_LOADING='ADDRECIPE_LOADING';
export const ADDRECIPE_ERROR='ADDRECIPE_ERROR';
export const ADDRECIPE_SUCCESS='ADDRECIPE_SUCCESS';

export const GETRECIPE_LOADING='GETRECIPE_LOADING';
export const GETRECIPE_ERROR='GETRECIPE_ERROR';
export const GETRECIPE_SUCCESS='GETRECIPE_SUCCESS';

export const GET_FEED_LOADING='GET_FEED_LOADING';
export const GET_FEED_ERROR='GET_FEED_ERROR';
export const GET_FEED_SUCCESS='GET_FEED_SUCCESS'

export const UPDATE_RECIPE_SUCCESS='UPDATE_RECIPE_SUCCESS';