export const ADDRECIPE_LOADING='ADDRECIPE_LOADING';
export const ADDRECIPE_ERROR='ADDRECIPE_ERROR';
export const ADDRECIPE_SUCCESS='ADDRECIPE_SUCCESS';

export const GETRECIPE_LOADING='GETRECIPE_LOADING';
export const GETRECIPE_ERROR='GETRECIPE_ERROR';
export const GETRECIPE_SUCCESS='GETRECIPE_SUCCESS';