export const GET_NONFRIEND_LOADING = "GET_NONFRIEND_LOADING";
export const GET_NONFRIEND_ERROR = "GET_NONFRIEND_ERROR";
export const GET_NONFRIEND_SUCCESS = "GET_NONFRIEND_SUCCESS";

export const POST_REQUEST_ERROR = "POST_REQUEST_ERROR";
export const POST_REQUEST_SUCCESS = "POST_REQUEST_SUCCESS";
export const POST_REQUEST_LOADING = "POST_REQUEST_LOADING";

export const GET_REQUESTSUSER_LOADING = "GET_REQUESTSUSER_LOADING";
export const GET_REQUESTSUSER_ERROR = "GET_REQUESTSUSER_ERROR";
export const GET_REQUESTSUSER_SUCCESS = "GET_REQUESTSUSER_SUCCESS";

export const POST_ACCEPTREQUEST_ERROR = "POST_ACCEPTREQUEST_ERROR";
export const POST_ACCEPTREQUEST_SUCCESS = "POST_ACCEPTREQUEST_SUCCESS";
export const POST_ACCEPTREQUEST_LOADING = "POST_ACCEPTREQUEST_LOADING";

export const POST_REJECTREQUEST_ERROR = "POST_REJECTREQUEST_ERROR";
export const POST_REJECTREQUEST_SUCCESS = "POST_REJECTREQUEST_SUCCESS";
export const POST_REJECTREQUEST_LOADING = "POST_REJECTREQUEST_LOADING";
