export const CREATE_USER_LOADING = 'CREATE-USER-LOADING';
export const CREATE_USER_ERROR = 'CREATE-USER-ERROR';
export const CREATE_USER_SUCCESS = 'CREATE-USER-SUCCESS';

export const LOGIN_USER_LOADING = 'LOGIN-USER-LOADING';
export const LOGIN_USER_ERROR = 'LOGIN-USER-ERROR';
export const LOGIN_USER_SUCCESS = 'LOGIN-USER-SUCCESS';

export const GET_LOGGEDUSER_LOADING = 'GET_LOGGEDUSER_LOADING';
export const GET_LOGGEDUSER_ERROR = 'GET_LOGGEDUSER_ERROR';
export const GET_LOGGEDUSER_SUCCESS = 'GET_LOGGEDUSER_SUCCESS';

export const RESET='RESET'

